[profile.default]
src = 'contracts'
out = "out"
libs = ["node_modules", "lib"]
test = 'test/forge'
cache_path  = 'cache_forge'
solc_version = '0.8.19'
evm_version = 'london'


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
