name: pr to sdk

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - contracts/**
      - deployments/**
      - hardhat.config.ts
      - wagmi.config.ts
      - .github/workflows/pr-sdk.yml
      - package.json
      - yarn.lock
permissions:
  contents: write

jobs:
  PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout our working repository
      - name: Conventional Changelog Action
        id: changelog
        uses: chromatic-protocol/conventional-changelog-action@v5.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: false
          pre-release: true
          git-push: true
          skip-on-empty: false
          # skip-version-file: false
          # skip-commit: false
      - uses: chromatic-protocol/action-setup-foundry-yarn@v2
      - name: generate wagmi code and PR
        run: |
          yarn wagmi generate
      - uses: chromatic-protocol/action-github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.PR_ACTION_APP_ID }}
          private_key: ${{ secrets.PR_ACTION_PRIVATE }}

      # make a PR to chromatic-protocol/liquidity-provider-sdk
      - uses: actions/checkout@v4
        with:
          repository: chromatic-protocol/liquidity-provider-sdk
          ref: main
          path: sdk
          token: ${{ steps.generate-token.outputs.token }}
      - run: |
          rm -rf sdk/src/gen/*
          cp -r wagmi/* sdk/src/gen/
      - name: pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: gen-lp
          path: sdk
          add-paths: |
            src/gen/**
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ github.event.pull_request.title }}
          title: Changes from contracts

      # make a PR to chromatic-protocol/chromatic-tasks
      - uses: actions/checkout@v4
        with:
          repository: chromatic-protocol/chromatic-tasks
          ref: main
          path: tasks
          token: ${{ steps.generate-token.outputs.token }}
      - run: |
          rm -rf tasks/src/gen/lp/*
          cp -r wagmi/* tasks/src/gen/lp/
      - name: pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: gen-lp
          path: tasks
          add-paths: |
            src/gen/lp/**
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ github.event.pull_request.title }}
          title: Changes from contracts
